

import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import "./globals.css";
import Layout from "./components/Layout";
import { ShoppingCartContextProvider } from "./context/ShoppingCartContextProvider";
import Footer from "./components/Footer";



export const metadata: Metadata = {
  title: "Create project App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
  
    <ShoppingCartContextProvider >
       <Layout> {children}</Layout>
       
    </ShoppingCartContextProvider>
      
     
      
      </body>
    </html>
  );
}

